    let colorSizes={
      "2":{
        size:64,
        color:"#eee4da",
          tcolor:"#776e65"
        },
        "4":{
            size:64,
           color: "#ede0c8",
          tcolor:"#776e65"
        },
        "8":{
        size:64,
        color:"#f2b179",
          tcolor:"#f9f6f2"
        },
        "16":{
              size:64,
        color:"#f59563",
          tcolor:"#f9f6f2"
        },
        "32":{
              size:64,
        color:"#f67c5f",
          tcolor:"#f9f6f2"
        },
        "64":{  
            size:64,
        color:"#f65e3b",
          tcolor:"#f9f6f2"
             },

        "128":{
              size:32,
        color:"#edcf72",
          tcolor:"#f9f6f2"
        },
        "256":{
              size:32,
        color:"#f65e3b",
          tcolor:"#f9f6f2"
        },
        "512":{
              size:32,
        color:"#edcf72",
          tcolor:"#f9f6f2"
        },
        "1024":{
              size:20,
        color:"#edcf72",
          tcolor:"#f9f6f2"
        },
        "2048":{
              size:20,
        color:"#f65e3b",
          tcolor:"",
          tcolor:"#f9f6f2"
        }
    }